### PR TITLE
Do not use column names KEY and VALUE they are reserved keywords in MySQL

### PR DESCRIPTION
**Pull request by r0b3rtk**
And hibernate will fail during startup

### CODE REVIEW

**Comment by Eernie** [comment]
Please only rename the column, not the field. Otherwise the output will change.

**Comment by cmkramer** [comment]
MySQL allows you to use reserved keywords if you escape them. I don't know if escaping is an option in the framework used though. In regular queries this comes down to using single quotes or backticks in query statements around the names of the respective columns

**Comment by r0b3rtk** [comment]
I'll try renaming only the columns, I didn't get it to work with the hbm2ddl option of Hibernate without renaming the getters/setters as well. Unfortunately, Hibernate does not automatically use escaping for reserved keywords that are used as column names :(

**Comment by Eernie** [comment]
You were right, hibernate doesn't generate the column by the name in the annotation. I've let the serialiser use the right names :)

**Pull request merged**
